### ISSUE TITLE
Errors in production are ugly

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#134]
A change in the API is the root cause, but the initial error causes a second error, when running in production:
```
[2020-02-20 14:46:55,101] ERROR in app: Request finalizing failed with an error while handling an error
Traceback (most recent call last):
  File "/opt/anaconda3/envs/portal-ui-37/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/envs/portal-ui-37/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/envs/portal-ui-37/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/envs/portal-ui-37/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/envs/portal-ui-37/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/envs/portal-ui-37/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/chuck/github/hubmap/portal-ui/context/app/routes_main.py", line 58, in details
    provenance = client.get_provenance(uuid)
  File "/Users/chuck/github/hubmap/portal-ui/context/app/api/client.py", line 106, in get_provenance
    provenance = json.loads(response['provenance_data'])
KeyError: 'provenance_data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/portal-ui-37/lib/python3.7/site-packages/flask/app.py", line 1969, in finalize_request
    response = self.process_response(response)
  File "/opt/anaconda3/envs/portal-ui-37/lib/python3.7/site-packages/flask/app.py", line 2268, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "/opt/anaconda3/envs/portal-ui-37/lib/python3.7/site-packages/flask/sessions.py", line 378, in save_session
    val = self.get_signing_serializer(app).dumps(dict(session))
  File "/opt/anaconda3/envs/portal-ui-37/lib/python3.7/site-packages/itsdangerous/serializer.py", line 166, in dumps
    payload = want_bytes(self.dump_payload(obj))
  File "/opt/anaconda3/envs/portal-ui-37/lib/python3.7/site-packages/itsdangerous/url_safe.py", line 42, in dump_payload
    json = super(URLSafeSerializerMixin, self).dump_payload(obj)
  File "/opt/anaconda3/envs/portal-ui-37/lib/python3.7/site-packages/itsdangerous/serializer.py", line 133, in dump_payload
    return want_bytes(self.serializer.dumps(obj, **self.serializer_kwargs))
  File "/opt/anaconda3/envs/portal-ui-37/lib/python3.7/site-packages/flask/json/tag.py", line 305, in dumps
    return dumps(self.tag(value), separators=(",", ":"))
  File "/opt/anaconda3/envs/portal-ui-37/lib/python3.7/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/opt/anaconda3/envs/portal-ui-37/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/opt/anaconda3/envs/portal-ui-37/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/anaconda3/envs/portal-ui-37/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/anaconda3/envs/portal-ui-37/lib/python3.7/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/opt/anaconda3/envs/portal-ui-37/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ValidationError is not JSON serializable
```
Can we fix that `ValidationError is not JSON serializable` so the real error is more obvious in the logs?

**Comment by mccalluc** [comment]
I haven't seen this recently, and I don't have a reproducer. Closing.
