### ISSUE TITLE
KeyError: 'provenance_data'

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#140]
On master, login and visit http://localhost:5000/browse/donor/5822aa2f0e9e1e9b07731de97109ef6d. I get this error:
```
Traceback (most recent call last):
  File "/opt/anaconda3/envs/portal-ui-37/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/anaconda3/envs/portal-ui-37/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/anaconda3/envs/portal-ui-37/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/envs/portal-ui-37/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/envs/portal-ui-37/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/envs/portal-ui-37/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/envs/portal-ui-37/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/envs/portal-ui-37/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/envs/portal-ui-37/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/envs/portal-ui-37/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/chuck/github/hubmap/portal-ui/context/app/routes_main.py", line 58, in details
    provenance = client.get_provenance(uuid)
  File "/Users/chuck/github/hubmap/portal-ui/context/app/api/client.py", line 110, in get_provenance
    provenance = json.loads(response['provenance_data'])
KeyError: 'provenance_data'
```

Suspect API change.

**Comment by mccalluc** [comment]
@cborromeo : I am happy to just disable this code for now and wait for the prov to be delivered as part of the ES response. If the ES is going to be a very long time in coming, or if a fix and redeploy of the API is trivial, then I could address this sooner. Thoughts?

**Comment by cborromeo** [comment]
@mccalluc I am looking through your code and trying to determine which API endpoint you are hitting.  Where is it deployed?  Also are you calling /entities/<identifier>/provenance?

**Comment by mccalluc** [comment]
- The API endpoint to hit is configuration which is not checked in, (it would be in context/instance/app.conf), but for local development I am using https://entity-api.test.hubmapconsortium.org.
- This is what I'm calling: (client.py)
```
        response = self._request(f'/entities/{uuid}/provenance')
        provenance = json.loads(response['provenance_data'])
```

**Comment by cborromeo** [comment]
got it.  thanks

**Comment by cborromeo** [comment]
I updated the entity API SmartAPI documents to reflect the current API here: http://smart-api.info/ui/0065e419668f3336a40d1f5ab89c6ba3

**Comment by mccalluc** [comment]
Since this bug was filed, the client code has changed (request is now made from useProvData.js, not client.py), that UUID no longer works, and maybe the server response has changed too? 

Closing.
