### ISSUE TITLE
500 from non-public HBM url

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#2033]
I logged in, added an unpublished item to my lists, logged out, and tried to visit it, and got a 500:

https://portal.hubmapconsortium.org/browse/HBM655.RVNL.232

The HBM redirect fail with an access-denied, instead of 500, if the user can't see an item.

**Comment by yuanzhou** [comment]
Error found from the AWS CloudWatch logging:

````
  | 2021-07-26T15:35:23.702-04:00 | [2021-07-26 19:35:23,699] ERROR in app: Exception on /browse/HBM655.RVNL.232 [GET]
  | 2021-07-26T15:35:23.702-04:00 | Traceback (most recent call last):
  | 2021-07-26T15:35:23.702-04:00 | File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
  | 2021-07-26T15:35:23.702-04:00 | response = self.full_dispatch_request()
  | 2021-07-26T15:35:23.702-04:00Copy  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request | File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
  | 2021-07-26T15:35:23.702-04:00Copy    rv = self.handle_user_exception(e) | rv = self.handle_user_exception(e)
  | 2021-07-26T15:35:23.702-04:00 | File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
  | 2021-07-26T15:35:23.702-04:00 | rv = self.dispatch_request()
  | 2021-07-26T15:35:23.702-04:00 | File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
  | 2021-07-26T15:35:23.702-04:00 | return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  | 2021-07-26T15:35:23.702-04:00 | File "./app/routes_main.py", line 83, in hbm_redirect
  | 2021-07-26T15:35:23.702-04:00 | entity = client.get_entity(hbm_id=f'HBM{hbm_suffix}')
  | 2021-07-26T15:35:23.702-04:00 | File "./app/api/client.py", line 99, in get_entity
  | 2021-07-26T15:35:23.702-04:00 | if len(uuid) == 32 and not self.nexus_token:
  | 2021-07-26T15:35:23.702-04:00 | TypeError: object of type 'NoneType' has no len()
````

Suggestion: set up some CloudWatch alerts in your sub account and get notified when there's a 500 error in the portal-ui docker log.
