### ISSUE TITLE
`zarr.errors.PathNotFoundError` with snRNA-seq

### ISSUE THREAD

**Issue by jswelling** [hubmapconsortium/portal-ui#2694]
This problem occurred on TEST and can be seen as https://portal.test.hubmapconsortium.org/browse/dataset/b95b348ffe6164e8c0123ca9d4f66ad2 .  The versions of the relevant workflows are:
* ingest-pipeline on branch release_1.9 at c584df65a9
* azimuth-annotate at c584df65a9  (this is downgraded from the current HEAD to avoid a separate bug)
* salmon-rnaseq v2.1.8
* portal-containers 1994f0f09 (current master HEAD)

**Comment by jswelling** [comment]
Portal Vitesse configuration info: 
![image](https://user-images.githubusercontent.com/14204985/174116646-64f366e6-684c-4d6a-9b4a-d0a49e7d9c51.png)

**Comment by mccalluc** [comment]
The browser console will not contain any useful information about the error, by design.

Server error:
```
[2022-06-16 23:08:48,589] ERROR in client: Building vitessce conf threw error: Traceback (most recent call last):
  File "/app/./app/api/client.py", line 182, in get_vitessce_conf_cells_and_lifted_uuid
    vitessce_conf = builder.get_conf_cells()
  File "/usr/local/lib/python3.9/site-packages/portal_visualization/builders/anndata_builders.py", line 56, in get_conf_cells
    z = zarr.open(adata_url, mode='r')
  File "/usr/local/lib/python3.9/site-packages/zarr/convenience.py", line 100, in open
    raise PathNotFoundError(path)
zarr.errors.PathNotFoundError: nothing found at path ''
```

Will ping @ilan-gold and @keller-mark on slack and see if they have ideas about next steps.

**Comment by keller-mark** [comment]
The error suggests that the url `adata_url` is an empty string or `None`/falsey (line 100 is a call to [normalize_storage_path](https://github.com/zarr-developers/zarr-python/blob/761bbedb8b500bb7668d8fde3dbcec5e60c72f53/zarr/util.py#L309)). I am not sure about what upstream code in `anndata_builders.py` would cause that to happen.

**Comment by mccalluc** [comment]
This is also occurring on TEST with https://portal.test.hubmapconsortium.org/browse/dataset/7a409b9cfa17824b78b82c78bd51a375. Using portal-visualization to reproduce locally:
```
src/vis-preview.py --json ~/Downloads/7a409b9cfa17824b78b82c78bd51a375.json
Using: RNASeqAnnDataZarrViewConfBuilder
Traceback (most recent call last):
  File "src/vis-preview.py", line 64, in <module>
    main()
  File "src/vis-preview.py", line 56, in main
    conf_cells = builder.get_conf_cells()
  File "/Users/chuck/github/hubmap/portal-visualization/src/portal_visualization/builders/anndata_builders.py", line 56, in get_conf_cells
    z = zarr.open(adata_url, mode='r')
  File "/opt/anaconda3/envs/portal/lib/python3.8/site-packages/zarr/convenience.py", line 105, in open
    raise PathNotFoundError(path)
zarr.errors.PathNotFoundError: nothing found at path ''
```
